### ISSUE TITLE
Database update goes into endless loop at 0%

### ISSUE THREAD

**Issue by domschl** [YeaSoft/plugin.video.mediathekview#3]
Some differential updates were successful.

At some point, update stalled at 0%
- Continuous display of "Applying database update 0%"

To be fixed:
- Message does not indicate which database (Better: "Updating Mediathek database: x%"). Once the module is tested, this message should probably be muted(?).
- Disabling database update in settings does not stop this stalled update.
- It would be useful to have a start/stop update button.

[no log messages]

**Comment by domschl** [comment]
service.Run()
                                              File "xxx.kodi/addons/plugin.video.mediathekview/service.py", line 60, in Run
                                                self.updater.Update( False )
                                              File "xxx/.kodi/addons/plugin.video.mediathekview/classes/updater.py", line 92, in Update
                                                self.Import( full )
                                              File "xxx/.kodi/addons/plugin.video.mediathekview/classes/updater.py", line 136, in Import
                                                fldt = datetime.datetime.strptime( value.strip(), "%d.%m.%Y, %H:%M" )
                                            TypeError: attribute of type 'NoneType' is not callable
                                            -->End of Python script error report<--
11:10:26.730 T:139665807992576 WARNING: CPythonInvoker(3, xxx/.kodi/addons/plugin.video.mediathekview/service.py): the python script "xxx/.kodi/addons/plugin.video.mediathekview/service.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N14PythonBindings31XBMCAddon_xbmc_Monitor_DirectorE,N9XBMCAddon7xbmcgui16DialogProgressBGE

Kracht bei: value.strip(), da value anscheined None ist.

**Comment by domschl** [comment]
Is a python problem: https://bugs.python.org/issue27400

**Comment by tuxpoldo** [comment]
Na großartig!
